version: '2'
networks:
  network:
services:
    ###---        Certificate Authorities Instants Section          ---###
  mailbox3-ca:
    container_name: mailbox3-ca.network.com
    image: hyperledger/fabric-ca 
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=mailbox-ca3
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.mailbox3.network.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.mailbox3.network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-new/peerOrganizations/mailbox3.network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - network
      ###---        Peer0 in Mailbox3 Instants Section          ---###
  couchdbpeer0mailbox3:
    container_name: couchdbpeer0mailbox3
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "9984:5984"
    networks:
      - network
  peer0.mailbox3.network.com:
    container_name: peer0.mailbox3.network.com
    extends:
      file:  base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.mailbox3.network.com
      - CORE_PEER_ADDRESS=peer0.mailbox3.network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.mailbox3.network.com:7051
      - CORE_PEER_LOCALMSPID=mailbox3MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbpeer0mailbox3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdbpeer0mailbox1
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-new/peerOrganizations/mailbox3.network.com/peers/peer0.mailbox3.network.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-new/peerOrganizations/mailbox3.network.com/peers/peer0.mailbox3.network.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053
    networks:
      - network
    ###---        Peer1 in Mailbox1 Instants Section          ---###
  couchdbpeer1mailbox1:
    container_name: couchdbpeer1mailbox1
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "6984:5984"
    networks:
      - network
  peer1.mailbox1.network.com:
    container_name: peer1.mailbox1.network.com
    extends:
      file:  base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.mailbox1.network.com
      - CORE_PEER_ADDRESS=peer1.mailbox1.network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.mailbox1.network.com:7051
      - CORE_PEER_LOCALMSPID=mailbox1MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbpeer1mailbox1:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdbpeer1mailbox1
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config/peerOrganizations/mailbox1.network.com/peers/peer1.mailbox1.network.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-config/peerOrganizations/mailbox1.network.com/peers/peer1.mailbox1.network.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8053:7053
    networks:
      - network