Organizations:
    - &mailbox3
        Name: mailbox3MSP
        ID: mailbox3MSP
        MSPDir: crypto-new/peerOrganizations/mailbox3.network.com/msp

        AnchorPeers:
            - Host: peer0.mailbox3.network.com
              Port: 7051