version: '2'
networks:
  network:
services:
  mailbox3-ca:
    container_name: mailbox3-ca.network.com
    image: hyperledger/fabric-ca:x86_64-1.1.0-preview
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_CA_NAME=mailbox-ca3
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.mailbox3.network.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.mailbox3.network.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/CA3_PRIVATE_KEY -b admin:adminpw -d'
    volumes:
      - ./crypto-new/peerOrganizations/mailbox3.network.com/ca/:/etc/hyperledger/fabric-ca-server-config
    networks:
      - network
  couchdbpeer0mailbox3:
    container_name: couchdbpeer0mailbox3
    image: hyperledger/fabric-couchdb:x86_64-1.1.0-preview
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "9984:5984"
    networks:
      - network
  peer0.mailbox3.network.com:
    container_name: peer0.mailbox3.network.com
    extends:
      file:  ../base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.mailbox3.network.com
      - CORE_PEER_ADDRESS=peer0.mailbox3.network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.mailbox3.network.com:7051
      - CORE_PEER_LOCALMSPID=mailbox3MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbpeer0mailbox3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdbpeer0mailbox3
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-new/peerOrganizations/mailbox3.network.com/peers/peer0.mailbox3.network.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-new/peerOrganizations/mailbox3.network.com/peers/peer0.mailbox3.network.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 11051:7051
      - 11053:7053
    networks:
      - network
  couchdbpeer1mailbox3:
    container_name: couchdbpeer1mailbox3
    image: hyperledger/fabric-couchdb:x86_64-1.1.0-preview
    environment:
      - COUCHDB_USER=
      - COUCHDB_PASSWORD=
    ports:
      - "10984:5984"
    networks:
      - network
  peer1.mailbox3.network.com:
    container_name: peer1.mailbox3.network.com
    extends:
      file:  ../base/peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.mailbox3.network.com
      - CORE_PEER_ADDRESS=peer1.mailbox3.network.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.mailbox3.network.com:7051
      - CORE_PEER_LOCALMSPID=mailbox3MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbpeer1mailbox3:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=
    depends_on:
      - couchdbpeer1mailbox3
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-new/peerOrganizations/mailbox1.network.com/peers/peer1.mailbox3.network.com/msp:/etc/hyperledger/fabric/msp
        - ./crypto-new/peerOrganizations/mailbox1.network.com/peers/peer1.mailbox3.network.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 12051:7051
      - 12053:7053
    networks:
      - network
  cli:
      container_name: climailbox3
      image: hyperledger/fabric-tools:x86_64-1.1.0-preview
      tty: true
      environment:
        - GOPATH=/opt/gopath
        - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
        - CORE_LOGGING_LEVEL=DEBUG
        - CORE_PEER_ID=cli
        - CORE_PEER_ADDRESS=peer0.mailbox3.network.com:7051
        - CORE_PEER_LOCALMSPID=mailbox3MSP
        - CORE_PEER_TLS_ENABLED=true
        - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/mailbox3.network.com/peers/peer0.mailbox3.network.com/tls/server.crt
        - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/mailbox3.network.com/peers/peer0.mailbox3.network.com/tls/server.key
        - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/mailbox3.network.com/peers/peer0.mailbox3.network.com/tls/ca.crt
        - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/mailbox3.network.com/users/Admin@mailbox3.network.com/msp
      working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
      command: /bin/bash -c 'sleep 10000000'
      volumes:
          - /var/run/:/host/var/run/
          - ../chaincode/:/opt/gopath/src/github.com/chaincode
          - ./crypto-new:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
          - ../scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
          - ../channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
      depends_on:
        - peer0.mailbox3.network.com
        - peer1.mailbox3.network.com
      networks:
        - network