# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
# Modified by Muhammad Salah <muhammad.salah@eg.ibm.com>
# Blockchain Weekends Program: Lab 1 "Blockchain Network Design"
#


version: '2' # We use this for versioning docker compose file. 
services:
  peer-base:
    image: hyperledger/fabric-peer:x86_64-1.0.3 # We added to tag a specific version of peers, we use fabric 1.0.3.
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock 
      # the following setting starts chaincode containers on the same
      # bridge network as the peers
      # https://docs.docker.com/compose/networking/
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_network        #We specify the virtual business network name we are dealing with in this project that we call "network"
      #- CORE_LOGGING_LEVEL=ERROR
      - CORE_LOGGING_LEVEL=DEBUG  #The debugging level can be set into "ERROR,INFO,DEBUG" we use Debug for development
      - CORE_PEER_TLS_ENABLED=true #TLS security can be thought of as the next generation of SSL, and it maintains the secure connectivity between the network.
      - CORE_PEER_GOSSIP_USELEADERELECTION=true # These are standard peer environment configurations for a basic network.
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/fabric/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/fabric/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/fabric/tls/ca.crt
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
  couchdb-base:
    image: hyperledger/fabric-couchdb:X86_64-1.0.3 # We provide the couchdb base, we could do that in a separate file, but it felt to be more logical associated with the Peer base.